-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelNumbers where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsNumbers

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsNumbers.Ident -> Result
transIdent x = case x of
  AbsNumbers.Ident string -> failure x

transExp :: AbsNumbers.Exp -> Result
transExp x = case x of
  AbsNumbers.Abs ident exp -> failure x
  AbsNumbers.App exp1 exp2 -> failure x
  AbsNumbers.Var ident -> failure x
